feat: Add Gnome EPUB files thumbnailing support
ublue-os/main pull request #457
Opened 2023-12-21 20:31 UTC by fiftydinar

Address
https://github.com/ublue-os/main/issues/449

2023-12-21 20:40 UTC, KyleGospo approved these changes

2023-12-22 03:11 UTC, castrojo requested changes

2023-12-22 03:11 UTC, castrojo commented on packages.json
> +                "gnome-epub-thumbnailer"
```suggestion
                "gnome-epub-thumbnailer",
```

2023-12-22 04:35 UTC, KyleGospo approved these changes

2023-12-22 13:27 UTC, castrojo approved these changes

2023-12-25 03:10 UTC, merged