feat: bump Fedora 40 to latest, Fedora 39 to stable and deprecate Fedora 38
ublue-os/main pull request #562
Opened 2024-04-22 18:49 UTC by p5

Remove kmods builds
Bump Fedora 40 to latest
Bump Fedora 39 to stable
Deprecate Fedora 38

2024-04-22 18:52 UTC, p5 commented on .github/workflows/reusable-build.yml
> +          elif [[ "${{ matrix.fedora_version }}" -eq "41" ]]; then
I know we don't really need this, but no point ripping this out when it'll be added in 4 months again.

2024-04-22 18:57 UTC, storopoli commented
Is this for the Fedora 40 release?
Then `latest` will de F40 and `gts` F39?

2024-04-22 19:04 UTC, bsherman commented
@p5 I don't think we should tie the release/promotion of F40 to stable/latest to removing F38 builds. Shouldn't removing F38 be a distinct act?

As much as I want to stop maintaining 38, I really am hesitant to drop those builds this week... feels like we should get a bit closer to upstream's EOL first.

2024-04-22 19:04 UTC, bsherman commented
>  `latest` will be F40 and `gts` F39?

yes

2024-04-22 19:05 UTC, p5 commented
> @p5 I don't think we should tie the release/promotion of F40 to stable/latest to removing F38 builds. Shouldn't removing F38 be a distinct act?
> 
> As much as I want to stop maintaining 38, I really am hesitant to drop those builds this week... feels like we should get a bit closer to upstream's EOL first.

Understood.  So including only the Containerfile ARG defaults and 
```
          if [[ "${{ matrix.fedora_version }}" -eq "39" ]]; then
            IS_LATEST_VERSION=false
            IS_STABLE_VERSION=true
            IS_GTS_VERSION=true
          elif [[ "${{ matrix.fedora_version }}" -eq "40" ]]; then
            IS_LATEST_VERSION=true
            IS_STABLE_VERSION=true
            IS_GTS_VERSION=false
          elif [[ "${{ matrix.fedora_version }}" -eq "41" ]]; then
```
is enough for tomorrow?

2024-04-22 19:15 UTC, p5 commented
Have repurposed this PR to only deprecate Fedora 38 and kmod builds.  Will bump Fedora 39 and 40 in [this PR](https://github.com/ublue-os/main/pull/563)

2024-04-22 21:22 UTC, bsherman commented
@p5 I would suggest that "deprecate" means "not recommended for use" but this PR will remove 38 so it cannot be used.

2024-04-24 18:00 UTC, dylanmtaylor requested changes
You should delete lxqt from image_name

2024-04-25 22:43 UTC, p5 commented
> You should delete lxqt from the image_name list.

Good catch
Done in [9508130](https://github.com/ublue-os/main/pull/562/commits/95081301c6f135815411a4a567849cb34e76cad6)

2024-04-27 06:57 UTC, bsherman commented
> Remove kmods builds Remove Fedora 38
> ### Do not merge until a few weeks after Fedora 40 dropped

Regarding the "when" of removing Fedora 38... we recently updated our governance document to make this more clear:

> Our goal is to build two currently supported versions of Fedora, the most recent and one previous version.

https://universal-blue.discourse.group/docs?topic=51

Given this update, we should be good to remove immediately.

2024-04-27 07:05 UTC, bsherman approved these changes

2024-04-27 07:06 UTC, KyleGospo approved these changes

2024-04-27 07:13 UTC, merged