chore(ci): use skopeo for more efficient upstream image introspection
ublue-os/main pull request #93
Opened 2023-03-30 17:38 UTC by castrojo

2023-03-30 18:41 UTC, joshua-stone requested changes
This needs `docker://` at the front:

https://github.com/ublue-os/nvidia/pull/79/files

2023-03-30 18:49 UTC, marcoceppi requested changes

2023-03-30 18:49 UTC, marcoceppi commented on .github/workflows/build.yml
> +          ver=$(skopeo inspect quay.io/fedora-ostree-desktops/${{ env.SOURCE_IMAGE }}:${{ matrix.major_version }} | jq -r '.Labels["org.opencontainers.image.version"]')
```suggestion
          ver=$(skopeo inspect docker://quay.io/fedora-ostree-desktops/${{ env.SOURCE_IMAGE }}:${{ matrix.major_version }} | jq -r '.Labels["org.opencontainers.image.version"]')
```

2023-03-31 04:12 UTC, marcoceppi approved these changes

2023-03-31 04:13 UTC, merged